let frutas = ["Manzana", "Banana", "Uva"];
frutas.push('Pera')
console.log(frutas)
frutas.unshift("Limon")
console.log(frutas)
frutas.pop()
console.log(frutas)
frutas.shift()
console.log(frutas)
console.log(frutas.length)